### ISSUE TITLE
Add README.md

### ISSUE THREAD

**Issue by skmlcd** [lahwaacz/arch-wiki-docs#11]
Can you please add a simple README.md file preferably with installation/dependency instructions?

I'm getting a error when try to run ```arch-wiki-docs.py```

I already ran these commands before (found on [arch package page](https://www.archlinux.org/packages/community/any/arch-wiki-docs/)):
```sudo pip install cssselect```
```sudo pip install lxml```
```sudo pip install simplemediawiki```

I'm on Ubuntu 14.04.

**Error** ```python3 arch-wiki-docs.py```:
```
Traceback (most recent call last):
  File "arch-wiki-docs.py", line 6, in <module>
    from simplemediawiki import build_user_agent
ImportError: No module named 'simplemediawiki'
```

---

```sudo pip install simplemediawiki```
```
Requirement already satisfied (use --upgrade to upgrade): simplemediawiki in /usr/local/lib/python2.7/dist-packages
Cleaning up...
```

**Comment by lahwaacz** [comment]
The code is written for and tested on Python 3, you may get random bugs on Python 2. The first error indicates that you may have the dependencies installed only for Python 2, while the second error is most likely [simplemediawiki](https://github.com/ianweller/python-simplemediawiki)'s problem. I'll see what I can do about the README...

**Comment by skmlcd** [comment]
Thanks.This problem could be Ubuntu related so I'm not going to bother you with that. Will probably switch to Arch in a few days anyway.

No pressure on README, but it's usually quite helpful to have one.
