### ISSUE TITLE
French translations are missing

### ISSUE THREAD

**Issue by kilbith** [lahwaacz/arch-wiki-docs#13]
Title says it all.

**Comment by lahwaacz** [comment]
That's because the French wiki is at wiki.archlinux.fr and the script currently downloads only from wiki.archlinux.org. I will have to migrate it to [wiki-scripts](https://github.com/lahwaacz/wiki-scripts) before this can be done.

**Comment by lahwaacz** [comment]
The French wiki was migrated to wiki.archlinux.org so it is included in the package now.
