### ISSUE TITLE
Redirects to category pages don't get resolved

### ISSUE THREAD

**Issue by nl6720** [lahwaacz/arch-wiki-docs#14]
For example: `en/Syslinux.html` has a link "Boot loaders" in it, it should link to `en/Category:Boot_loaders.html`, but instead it links to the non-existent `en/Boot_loaders.html`.

**Comment by lahwaacz** [comment]
Should be fixed in https://github.com/lahwaacz/arch-wiki-docs/commit/15545a8b1df0b3aa6e507e21a1505d4d828ee024, thanks for reporting.
