### ISSUE TITLE
Fails under Python 3:

### ISSUE THREAD

**Issue by artkpv** [lahwaacz/arch-wiki-docs#18]
This is in order to install Arch Linux having Win8 machine only, to have the wiki on USB flash when installing the Arch. 

Steps:
```
> git clone ... 
> pip install simplemediawiki
> py .\arch-wiki-docs.py
Traceback (most recent call last):
  File ".\arch-wiki-docs.py", line 6, in <module>
    from simplemediawiki import build_user_agent
  File "C:\Python\lib\site-packages\simplemediawiki.py", line 179
    print test_api_url
                     ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(test_api_url)?
```

**Comment by lahwaacz** [comment]
The error message points to [simplemediawiki](https://github.com/iliana/python-simplemediawiki), which has something different on [line 179](https://github.com/iliana/python-simplemediawiki/blob/develop/simplemediawiki.py#L179). You are probably using an old version.
