### ISSUE TITLE
Fails with subpages with language tag

### ISSUE THREAD

**Issue by rffontenelle** [lahwaacz/arch-wiki-docs#20]
Subpages now have language tag in both parts (parent page and subpage) after talk in [help_talk:I18n#Localized_subpages](https://wiki.archlinux.org/index.php/Help_talk:I18n#Localized_subpages) and since [Help:I18n#Page_titles](https://wiki.archlinux.org/index.php/Help:I18n#Page_titles) has been updated.

For sub-pages that have language tag in both parts, arch-wiki-docs still downloads the subpage correctly, but the subpage is kept in the language root directory in an unrecognizable filename (e.g. "2252df9ed53fcf7fbb097a1d379a8158.html") without creating a subdirectory to hold the subpages.

subpages without language tag in the parent page part are not affect -- they receive the correct filename and go to the expected subdirectory.

**Comment by lahwaacz** [comment]
The hashed titles are used because of the `--safe-filenames` flag, it has nothing to do with subpages.

https://github.com/lahwaacz/arch-wiki-docs/blob/master/ArchWiki/ArchWiki.py#L187-L191

**Comment by rffontenelle** [comment]
Oh I see. I assumed it was the language tag in the part page, because it was a recent change and I have never notice this issue before.
