### ISSUE TITLE
[feature request] add archlinux manual html pages

### ISSUE THREAD

**Issue by 20NE** [lahwaacz/arch-wiki-docs#22]
archlinux  announce newest public service: A manual pages indexing site at [man.archlinux.org](https://man.archlinux.org/)  that publishes the man pages of all packages.

Hope that manual html pages can add to arch-wiki-docs.

Cheers.

**Comment by lahwaacz** [comment]
This project is for the _wiki_ pages, manual pages would have to be collected in a different project. But I don't see much use for that, since everybody can easily access all man pages for the packages they have installed.
