### ISSUE TITLE
Handle redirects

### ISSUE THREAD

**Issue by lahwaacz** [lahwaacz/arch-wiki-docs#3]
Redirect pages are currently not managed, which leaves many broken links.
- option 1: create symlinks to the target page - does not work with redirects to sections
- option 2: collect list of redirect pages and manually replace affected links

**Comment by lahwaacz** [comment]
Should be fixed in https://github.com/lahwaacz/arch-wiki-docs/commit/d76535d77f335442e886e6def609a372650ba9af.

**Comment by 20NE** [comment]
This issue seems still exist.
